### ISSUE TITLE
how about OSM

### ISSUE THREAD

**Issue by tigernassau** [andre/geocoder#1]
excellent - geocoding for Crystal is very needed BUT would be nicer to have OSM target  - perhaps we could adapt this code if we have time.  OSM is not "free to start" instead it is free forever !

**Comment by andre** [comment]
Sure why not! [Added](https://github.com/andre/geocoder/commit/d8a6e5dace67fc428e0b973e6e9f9449753fd395#diff-565688fecc9dc02a792c1f1d68ca3450). Note though that the [usage guidelines are fairly restrictive](https://operations.osmfoundation.org/policies/nominatim/). Also, I found the formatting of the returned addresses to be pretty funky. Someone else might be able to improve on this.
